{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 159433,
          "sha512": "7a8d2d88bcd230f7e1f6184238399895987df682bf9fc20790a413292145c9f7d9c1ac70621fc25ac8119bb0f3e2334b9424cf670b75fbc38f0171fe921a8661",
          "sha256": "63287cfb09ed422fee451712315e1299e85188f1426a2911af47cb38ecbb5c63",
          "sha1": "0c16369b832aa9a322a0c542d2e1f7a498cc1fdc",
          "md5": "b915db3ed919c90d0e7bb62d0f99817b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 159433,
          "sha512": "7a8d2d88bcd230f7e1f6184238399895987df682bf9fc20790a413292145c9f7d9c1ac70621fc25ac8119bb0f3e2334b9424cf670b75fbc38f0171fe921a8661",
          "sha256": "63287cfb09ed422fee451712315e1299e85188f1426a2911af47cb38ecbb5c63",
          "sha1": "0c16369b832aa9a322a0c542d2e1f7a498cc1fdc",
          "md5": "b915db3ed919c90d0e7bb62d0f99817b"
        }
      ]
    }
  ]
}
