{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 159434,
          "sha512": "e2c3e42dbb9ae1d475b4d06cbaf0f5b6dab64292d03a2626d0241dc15253b4532cb052e09204d1e1811fff2c15687e6ecad2afea0e46d751fa2d11c792f2e86c",
          "sha256": "04800f7e363c04996cd3fe9b165b7c6a863d2398fdff8b1cd14b6bb3de1d839c",
          "sha1": "6038bef01cbb3eaad7a5f9eea2f09dfaba8cbe97",
          "md5": "9b12a66676b8fab87d609d27476811fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 159434,
          "sha512": "e2c3e42dbb9ae1d475b4d06cbaf0f5b6dab64292d03a2626d0241dc15253b4532cb052e09204d1e1811fff2c15687e6ecad2afea0e46d751fa2d11c792f2e86c",
          "sha256": "04800f7e363c04996cd3fe9b165b7c6a863d2398fdff8b1cd14b6bb3de1d839c",
          "sha1": "6038bef01cbb3eaad7a5f9eea2f09dfaba8cbe97",
          "md5": "9b12a66676b8fab87d609d27476811fa"
        }
      ]
    }
  ]
}
