{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158841,
          "sha512": "f671dee44c39ceed7df70eed4d36637a027c4a4c19a83c751c03cac577b9e4ffa8d810fd39bcd3c7a69b075d1832a4f978f03e97e929a468ed21b1f9f778dd0c",
          "sha256": "ae0459b2ba16e8dd96d7d8e6695d523ebbfa6d5239434eacec0eafe138334fdc",
          "sha1": "d0d4c9911688e9ff5c6099a3bd5291c0e65a3d26",
          "md5": "b38c2687de3f86db8b670b4cc3c8e7c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158841,
          "sha512": "f671dee44c39ceed7df70eed4d36637a027c4a4c19a83c751c03cac577b9e4ffa8d810fd39bcd3c7a69b075d1832a4f978f03e97e929a468ed21b1f9f778dd0c",
          "sha256": "ae0459b2ba16e8dd96d7d8e6695d523ebbfa6d5239434eacec0eafe138334fdc",
          "sha1": "d0d4c9911688e9ff5c6099a3bd5291c0e65a3d26",
          "md5": "b38c2687de3f86db8b670b4cc3c8e7c7"
        }
      ]
    }
  ]
}
