{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 159436,
          "sha512": "36b32a0b048a0ed527f84abfa503806482dc0df15a2fe549e789e876967ff74dbf51d4a3390ffdd36892a7c5c6acf895be4b6ae9b0f2a6aae0428bda40c0096c",
          "sha256": "4b417542927302340796c0a517c6393661102247b7ac73215685a8e3bcd5a319",
          "sha1": "eacbb548e4af8575f15395630cda5d187222012a",
          "md5": "e2077f0f1b64dd7f348cc66b2e572fb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 159436,
          "sha512": "36b32a0b048a0ed527f84abfa503806482dc0df15a2fe549e789e876967ff74dbf51d4a3390ffdd36892a7c5c6acf895be4b6ae9b0f2a6aae0428bda40c0096c",
          "sha256": "4b417542927302340796c0a517c6393661102247b7ac73215685a8e3bcd5a319",
          "sha1": "eacbb548e4af8575f15395630cda5d187222012a",
          "md5": "e2077f0f1b64dd7f348cc66b2e572fb9"
        }
      ]
    }
  ]
}
